### ISSUE TITLE
inconsistent blips and complete lack of response on librem 13

### ISSUE THREAD

**Issue by saltthefries** [kylerankin/psmouse-byd-dkms#2]
I'm using this driver against Debian Linux kernel 4.3.3-7 (2016-01-19) in stretch (testing) on a Librem 13, and I get occasional blips in responsiveness from the touchpad that generate errors in dmesg.
I have also had some incidents where the touchpad has completely failed to respond and is only recovered when powering the machine off completely. There may be a hardware issue, but I've seen this on two different machines (one with a seemingly unrelated LCD problem).

I'm attaching 3 logs (grepped for byd)
[bydfailure1.txt](https://github.com/kylerankin/psmouse-byd-dkms/files/111485/bydfailure1.txt) - a complete failure to respond until power off / on
[bydissue2.txt](https://github.com/kylerankin/psmouse-byd-dkms/files/111486/bydissue2.txt) - a blip in responsiveness
[bydissue3.txt](https://github.com/kylerankin/psmouse-byd-dkms/files/111488/bydissue3.txt) - another blip

Let me know if there is any other information that would be helpful. I don't know how to explicitly recreate the issue, but it happens pretty reliably in a 1-2 hour session of web browsing, etc.

**Comment by kylerankin** [comment]
Unfortunately I just take the driver from the upstream purism kernel and repackage it so it works with DKMS so it would probably be best to file any bugs you are getting with the driver in their project at https://github.com/purism/linux/
