### ISSUE TITLE
Problems installing on 4.2.x kernel or greater

### ISSUE THREAD

**Issue by jacklenox** [kylerankin/psmouse-byd-dkms#9]
I am experiencing a similiar issue to what I had before on a 3.x kernel, but on anything above 4.1.20. This is the error from the log:

```
DKMS make.log for psmouse-byd-0.2 for kernel 4.2.8-040208-generic (x86_64)
Mon Mar 28 14:16:03 BST 2016
make: Entering directory `/usr/src/linux-headers-4.2.8-040208-generic'
Makefile:659: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
  CC [M]  /var/lib/dkms/psmouse/byd-0.2/build/src/psmouse-base.o
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
make[1]: *** [/var/lib/dkms/psmouse/byd-0.2/build/src/psmouse-base.o] Error 1
make: *** [psmouse.ko] Error 2
make: Leaving directory `/usr/src/linux-headers-4.2.8-040208-generic'
```

Any ideas of what this means? I'm trying to move beyond the 4.1.20 kernel because I've noticed that anything below 4.2 seems to mean that two-finger scroll won't work (on elementary OS Freya which is based on Ubuntu). When I upgrade to anything from 4.2 up, two finger scrolling becomes available as an option in my settings, but the default driver for the touchpad doesn't work properly – the cursor sticks in the top right hand corner of the screen.

**Comment by b3** [comment]
Can you post the result of `gcc --version`?
BTW on Ubuntu 15.10 with kernel 4.2.0, two finger scrolling does not work either (the option is visible but can not be selected and using `synclient` does not help either).

**Comment by jacklenox** [comment]
I found a few sites mentioning this, but I don't think it's the issue. Output is:

```
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by b3** [comment]
The missing option `-fstack-protector-strong` appears only in gcc 4.9 (just compare https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/Optimize-Options.html#Optimize-Options and https://gcc.gnu.org/onlinedocs/gcc-4.9.3/gcc/Optimize-Options.html#Optimize-Options).

I thus really think that, the mismatch gcc version should be the trouble. I am afraid your distro does not offer recent enough gcc yet.

**Comment by fluffypony** [comment]
I'm hitting the same problem on stock Qubes 3.1. It appears that, out the box, dom0 runs Fedora 20, which only has gcc 4.8 available. Since it needs to be built against a particular kernel I can't build this in a Fedora 23 VM and then just copy the compiled module to dom0.

What are the workable options, since this is specifically meant to help the Qubes issue?

**Comment by kylerankin** [comment]
For Qubes, the Qubes team has built a custom kernel and dkms rpm based on this driver that makes psmouse modular. You have to add the unstable Qubes repository to make it work or I suppose you could manually install the RPMs from here: http://yum.qubes-os.org/r3.1/unstable/dom0/fc20/rpm/

**Comment by kylerankin** [comment]
As far as issues with other versions of GCC, I've only tested building this on Debian stretch and on Qubes. Qubes requires a special kernel that makes psmouse modular. In general though I would hit up the Purism upstream team responsible for the driver itself as I just repackage it, if you are having issues getting the module to work with older environments.
